FROM python:3.11.3-slim AS Bot

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

ENV TG_TOKEN ${TG_TOKEN}
ENV SEAFILE_URL ${SEAFILE_URL}
ENV SEAFILE_EMAIL ${SEAFILE_EMAIL}
ENV SEAFILE_PASSWORD ${SEAFILE_PASSWORD}
ENV SEAFILE_REPO ${SEAFILE_REPO}
ENV ALLOWED_IDS ${ALLOWED_IDS}
ENV DEVELOPER_CHAT_ID ${DEVELOPER_CHAT}

RUN apt-get update
RUN apt-get install -y python3 python3-pip python-dev build-essential python3-venv

RUN mkdir -p /codebase
ADD . /codebase
WORKDIR /codebase

RUN pip3 install -r requirements.txt
RUN chmod +x /codebase/bot/bot.py

CMD python3 /codebase/bot/bot.py;
